# Generated by Django 6.0 on 2026-06-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
    ]
