# Generated by Django 6.0 on 2026-06-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_attendence_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
    ]
