# Generated by Django 6.0 on 2026-06-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_attendence_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
